### ISSUE TITLE
PointCloud2 from Multisense SL in SCS

### ISSUE THREAD

**Issue by velinddimitrov** [ihmcrobotics/ihmc_valkyrie_ros#1]
Would it be possible to add support for PointCloud2 msg type from the Multisense in the SL simulator?

**Comment by velinddimitrov** [comment]
@dljsjr sorry doug, not sure if you wanted this feature request in this repo or another one. Let me know if you want it moved.

**Comment by dljsjr** [comment]
We should move it to https://github.com/ihmcrobotics/ihmc-open-robotics-software because it impacts Atlas as well. And any simulation that would use a Multisense SL.

**Comment by velinddimitrov** [comment]
Moved to ihmc-open-robotics-software.
