### ISSUE TITLE
Sudden unexpected foot movement causes Valkyrie to fall

### ISSUE THREAD

**Issue by jordan-palacios** [ihmcrobotics/ihmc_valkyrie_ros#12]
Hello,

We are currently working for the space robotics challenge with Valkyrie. The latest version of the ihmc packages are being used.

We have setup a test that does multiple runs of the same set of footsteps. Walking is fine but sometimes, like once every 50 tries, one of Valkyries foot does a sudden movement while in the air and causes the whole robot to fall.

Here is a quick example video: https://streamable.com/fykeq

Perhaps, we are doing something wrong?

Next is a download link with the tar file with the full gazebo log in order to reproduce the simulation. I also included a recorded bag file with the following topics:

- /clock
- /hardware_joint_states
- /ihmc_ros/valkyrie/control/footstep_list
- /ihmc_ros/valkyrie/output/footstep_status
- /rosout
- /rosout_agg
- /tf

If you need anything more please let me know.

https://www.dropbox.com/s/wfe7heslxrnutgt/walk_failure.tgz?dl=0

**Comment by dljsjr** [comment]
Hey @jordan-palacios,

For this sort of failure often the data we need won't be in the Gazebo logs or in the rosbag. I'm in touch with the folks over at OSRF right now to talk about setting up instructions to allow competitors to run logging system for all of the control algorithm internals. You should have everything already with the current packages installed but there aren't any valid configurations or roslaunch XML's for it yet.

**Comment by jordan-palacios** [comment]
Thanks for you answer @dljsjr.

Looking forward to those instructions then!
