### ISSUE TITLE
valkyrie_ros_api.launch leads to lots of open files

### ISSUE THREAD

**Issue by scpeters** [ihmcrobotics/ihmc_valkyrie_ros#15]
| Required Info ||
|---|---|
|Version or commit hash|https://github.com/ihmcrobotics/ihmc_valkyrie_ros/commit/edecd31683904d65d2cbec626b3971113f35caa5, https://github.com/ihmcrobotics/ihmc-open-robotics-software/commit/c787635debeb97ab02c44212954fd4aa9efb050b|
|Operating System|Ubuntu 14.04 (in docker)|
|ROS Version|indigo, with gazebo7|

####Steps to reproduce issue
If I load Valkyrie in gazebo with `val_sim_gazebo_sync.launch`, then `val_wholebody_control_gazebo.launch` and run `lsof | wc -l`, I see about 86000 open files. After launching `valkyrie_ros_api.launch`, however, I see over 1.5 million open files, and a full 670k are FIFO pipes opened by java. I have no idea why, but it seems like a lot.

####Expected behavior
Is this a normal number of open files? We have had users complain about an excessive number of open files on bitbucket:

* https://bitbucket.org/osrf/srcsim/issues/134/javaioioexception-too-many-open-files

####Actual behavior
Lots of open files

####Contributors with relevant knowledge or expertise (optional)
@dljsjr

**Comment by dljsjr** [comment]
Interesting.

My guess? We do a ton of asynchronous I/O in the API node, so there's probably a whack of epoll FDs and thread pools open. 670K seems pretty extreme though.

This might be closely related to https://github.com/ihmcrobotics/ihmc-open-robotics-software/issues/93

We have yet to determine if this resource leak is in the JVM or in our intraprocess async stack.

cc @jespersmith @btshrewsbury
