### ISSUE TITLE
Can not find us/ihmc/rosControl/IHMCRosControlJavaBridge

### ISSUE THREAD

**Issue by robograffitti** [ihmcrobotics/ihmc_valkyrie_ros#8]
I installed ihmc_valkyrie_ros with srcsim (https://bitbucket.org/osrf/srcsim/).

Then, I found that val_wholebody_control_gazebo.launch fails with the error of not finding IHMCRosControlJavaBridge with this message:
[INFO] [WallTime: 1478230606.254090] [4.270000] Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [WallTime: 1478230606.256299] [4.273000] Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [WallTime: 1478230606.257587] [4.275000] Loading controller: ihmc_valkyrie_control_java_bridge
[ INFO] [1478230606.294394211, 4.312000000]: Starting JVM with arguments: -Djava.class.path=ValkyrieController.jar -XX:+UseSerialGC -Xmx4g -Xms4g -XX:NewSize=3g -XX:MaxNewSize=3g -XX:CompileThreshold=1000 -verbosegc -Djava.library.path=lib/
Starting Java VM from path  /home/leus/valkyrie
Started Java VM: success
Cannot find class us/ihmc/rosControl/IHMCRosControlJavaBridge
[ERROR] [1478230606.369116100, 4.385000000]: Cannot find update method
[ERROR] [1478230606.369206855, 4.385000000]: Initializing controller 'ihmc_valkyrie_control_java_bridge' failed
[ INFO] [1478230606.369381399, 4.385000000]: Stopping VM
Exception in thread "main" java.lang.NoClassDefFoundError: us/ihmc/rosControl/IHMCRosControlJavaBridge
Caused by: java.lang.ClassNotFoundException: us.ihmc.rosControl.IHMCRosControlJavaBridge
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)

I only found its header file and shared object but I don't know where the class file is.

leus@y-tanaka-silver-stone:~$ locate IHMCRosControlJavaBridge
/opt/ros/indigo/include/ros_controllers/IHMCRosControlJavaBridge.h

leus@y-tanaka-silver-stone:~$ locate ihmc_ros_control_java_bridge
/opt/ros/indigo/lib/libihmc_ros_control_java_bridge.so

Could you tell me how to load the class in this controller program?

**Comment by nmertins** [comment]
Hi Yoshimaru. I just set up a clean environment and verified the install instructions found here:
https://bitbucket.org/osrf/srcsim/wiki/system_setup
produce a working sim. Did you see any errors during setup? The only problem I saw was a typo in step 11 which should be:
`roslaunch ihmc_valkyrie_ros valkyrie_warmup_gradle_cache.launch`

**Comment by nmertins** [comment]
And it looks like they just fixed that typo in their instructions.

**Comment by robograffitti** [comment]
valkyrie_controller.tar.gz was added a few days ago, and it solved this issue!
